### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by 1010Manoj** [prasunroy/ocr#1]
Hi, I followed the entire installation process with success.
I have also installed tensorflow (not mentioned as a requirement) using `$pip install tensorflow`.
I am getting the following error:

>Using TensorFlow backend.
2019-01-02 13:31:23.936779: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted (core dumped)

Can anyone help? Thanks.

**Comment by prasunroy** [comment]
You need to use **Theano** as the backend of Keras. By default Keras uses Tensorflow as backend. Detailed instructions about switching from one backend to another can be found [here](https://keras.io/backend/#switching-from-one-backend-to-another).
