### ISSUE TITLE
Recognition doses not work - server returns ERROR 500

### ISSUE THREAD

**Issue by gakowalski** [prasunroy/ocr#2]
Error message in browser:

> recognize: Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

Traceback from server:

> 127.0.0.1 - - [05/Jun/2019 10:50:51] "[1m[35mPOST /recognize HTTP/1.1[0m" 500 -
> Traceback (most recent call last):
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "F:\Python\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
>     raise value
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "F:\Python\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
>     raise value
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "F:\Python\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "F:\IT\ocr\app.py", line 138, in recognize
>     prediction = ocr(model, dfile, segmentation, engine, debug=False)[0]
>   File "F:\IT\ocr\ocrlib.py", line 104, in ocr
>     [image_scan, image_rois] = imscanC(file, bbox_width=2, verbose=debug)
>   File "F:\IT\ocr\scan.py", line 332, in imscanC
>     cv2.CHAIN_APPROX_NONE)
> ValueError: not enough values to unpack (expected 3, got 2)

My machine:

> (base) F:\IT\ocr>python --version
> Python 3.7.3

> (base) F:\IT\ocr>ver
> Microsoft Windows [Version 10.0.17134.765]

conda / anacoda / keras and others are all up-to-date

**Comment by prasunroy** [comment]
This is probably because you are using OpenCV v.4.0.0+.

Try changing line 327-332 in `scan.py`

From:
```python
if opencv == 2:
    (contours, _) = cv2.findContours(image_th.copy(), cv2.RETR_EXTERNAL,
                                     cv2.CHAIN_APPROX_NONE)
else:
    (_, contours, _) = cv2.findContours(image_th.copy(), cv2.RETR_EXTERNAL,
                                        cv2.CHAIN_APPROX_NONE)
```

To:
```python
if opencv == 3:
    (_, contours, _) = cv2.findContours(image_th.copy(), cv2.RETR_EXTERNAL,
                                        cv2.CHAIN_APPROX_NONE)
else:
    (contours, _) = cv2.findContours(image_th.copy(), cv2.RETR_EXTERNAL,
                                     cv2.CHAIN_APPROX_NONE)
```

**Comment by gakowalski** [comment]
Thanks for your quick response. Now the server traceback changed into:

> Using Theano backend.
> Traceback (most recent call last):
>   File "app.py", line 30, in <module>
>     model_en_numbers = cnn(config.i_shape, config.n_class_en_numbers)
>   File "F:\IT\ocr\models.py", line 31, in cnn
>     input_shape=i_shape))
>   File "F:\Python\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 165, in add
>     layer(x)
>   File "F:\Python\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
>     self.build(unpack_singleton(input_shapes))
>   File "F:\Python\Anaconda3\lib\site-packages\keras\layers\convolutional.py", line 141, in build
>     constraint=self.kernel_constraint)
>   File "F:\Python\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "F:\Python\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 249, in add_weight
>     weight = K.variable(initializer(shape),
>   File "F:\Python\Anaconda3\lib\site-packages\keras\initializers.py", line 218, in __call__
>     dtype=dtype, seed=self.seed)
>   File "F:\Python\Anaconda3\lib\site-packages\keras\backend\theano_backend.py", line 2600, in random_uniform
>     return rng.uniform(shape, low=minval, high=maxval, dtype=dtype)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py", line 872, in uniform
>     rstates = self.get_substream_rstates(nstreams, dtype)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\configparser.py", line 117, in res
>     return f(*args, **kwargs)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py", line 779, in get_substream_rstates
>     multMatVect(rval[0], A1p72, M1, A2p72, M2)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py", line 62, in multMatVect
>     [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o, profile=False)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\compile\function.py", line 317, in function
>     output_keys=output_keys)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
>     output_keys=output_keys)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
>     fn = m.create(defaults)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 1715, in create
>     input_storage=input_storage_lists, storage_map=storage_map)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
>     storage_map=storage_map)[:3]
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
>     impl=impl))
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
>     no_recycling)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\op.py", line 858, in make_c_thunk
>     output_storage=node_output_storage)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1217, in make_thunk
>     keep_lock=keep_lock)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1157, in __compile__
>     keep_lock=keep_lock)
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1609, in cthunk_factory
>     key = self.cmodule_key()
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1300, in cmodule_key
>     c_compiler=self.c_compiler(),
>   File "F:\Python\Anaconda3\lib\site-packages\theano\gof\cc.py", line 1379, in cmodule_key_
>     np.core.multiarray._get_ndarray_c_version())
> AttributeError: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'")

**Comment by prasunroy** [comment]
It turns out that Theano only supports Python >= 3.4 and < 3.6. So you need to use Python 3.4 or 3.5.

```
conda create -n ocr python=3.5
conda activate ocr
conda install theano
pip install flask h5py keras matplotlib numpy opencv-python
git clone https://github.com/prasunroy/ocr.git
cd ocr
python app.py
```

I pushed changes [390b1af](https://github.com/prasunroy/ocr/commit/390b1af5766c365d7ca3498550cc8b5a43b14478) to fix compatibility issues with OpenCV 4.x and Theano 1.x.

> **NOTE:** Theano is no longer being developed. It is recommended to switch to a different framework. With the above changes the OCR should run but the recognition rate may be very poor for some reason. The actual performance can be tested in this [demo](http://prasun.pythonanywhere.com/).

**Comment by ghost** [comment]
The result is not very promising. It is not working well with handwritten digits or text. Any way to improve it?
